# Generated by Django 6.0.3 on 2026-04-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=100)),
                ('rating_value', models.CharField(max_length=50)),
                ('inspection_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('user_rating', models.FloatField()),
                ('hygiene_score', models.FloatField()),
            ],
        ),
    ]
