# Generated by Django 6.0.5 on 2026-06-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurant_admin_notes'),
        ('accounts', '0010_admin_fields'),
    ]

    operations = [
    ]
