# Generated by Django 6.0.5 on 2026-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_ownerreviewflag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerreportresponse',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence_documents/'),
        ),
    ]
