# Generated by Django 5.0 on 2026-06-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_ownerreportresponse_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='hygieneissuereport',
            name='image_proof',
            field=models.FileField(blank=True, null=True, upload_to='hygiene_reports/images/'),
        ),
        migrations.AddField(
            model_name='ownerreportresponse',
            name='evidence_image',
            field=models.FileField(blank=True, null=True, upload_to='evidence_images/'),
        ),
    ]
